mattosaurus/PgpCore

PgpCore/PGP.cs, README.md
It is very useful to pass more than one public key sometimes. 
This can be done now !
=> Added support for encrypting files for/with multiple publickeys

PgpCore/PGP.cs, PgpCoreTest/Program.cs, README.md
Merge multiple keys update by deibertf into master
=> Merge in multiple keys update

PgpCore/Utilities.cs
The choice was to either enable multikey support to ChoPGP or to fix this repo. 😊
I also made the method internal out of reflex.
=> Portet from ChoPGP in order to make it work with my Yubikey's subkey

PgpCore.Tests/UnitTests.cs, PgpCore/PGP.cs
=> Handle large files

PgpCore.Tests/PgpCore.Tests.csproj, PgpCore.Tests/UnitTests.cs, PgpCore/PGP.cs, PgpCore/PgpCore.csproj, PgpCore/Streams.cs, PgpCore/Utilities.cs
Update to make async first #28 (apart from Verify) and to better handle large files #29.
=> Aysnc updates and large file handling

PgpCore/PGP.cs, README.md
=> GenerateKey should overwrite file

README.md
=> Fix ClearSignStream

PgpCore/PgpCore.csproj
=> Add .Net Core 2.2 and 3.1 as target frameworks

PgpCore/PGP.cs
The [RFC](https://tools.ietf.org/html/rfc4880#section-5.6) states a compressed data packet may follow a signature:
> The Compressed Data packet contains compressed data.  Typically, this
packet is found as the contents of an encrypted packet, or following
a Signature or One-Pass Signature packet, and contains a literal data
packet.
The Decrypt method currently throws an exception in this scenario. I made the change to handle a compressed data packet following a signature.
The file producing the exception does decrypt correctly using other libraries such as Kleopatra.
=> Handle compressed data packet following signature

PgpCore/PgpCore.csproj
- Return assembly strong name
- Increase major because of this https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/breaking-changes#binary-breaking-change
https://github.com/mattosaurus/PgpCore/issues/102
=> Return assembly strong name

PgpCore.Tests/UnitTests/UnitTestsSync.cs, PgpCore/PGP.cs
Added support for `--emit-version` and `--no-emit-version` flags when generating key pair
=> Added  support for --emit-version and --no-emit-version

PgpCore/PGP.cs
Support for reading recipients keyIds of encrypted files and streams.
=> Add `GetRecipients` support

PgpCore.Tests/UnitTests/UnitTestsAsync.cs, PgpCore.Tests/UnitTests/UnitTestsSync.cs, PgpCore/PGP.cs
=> DecryptAndVerify verify that a signature exist for compressed files

PgpCore/EncryptionKeys.cs
Update EncryptionKeys properties to be lazily loaded for #122
=> Lazy encryption keys

PgpCore/PGP.cs, PgpCore/PgpCore.csproj, PgpCore/Utilities.cs
=> Fix missing pgp signature list

PgpCore/Utilities.cs
Reverts mattosaurus/PgpCore#159
=> Revert "Allow for subkeys to be used for encryption"

PgpCore/PgpCore.csproj
=> Update bouncy castle version

PgpCore/PgpCore.csproj
Update project release version so changes in #199 can be published.
=> Update project version to v5.10.0

PgpCore/PGP.cs
=> Add message is PgpSignatureList on Decrypt and DecryptAndVerify #214

PgpCore/PGP.cs
=> Added key preferences for PGP generated keys

PgpCore.Tests/UnitTests/UnitTestsAsync.cs, PgpCore.Tests/UnitTests/UnitTestsSync.cs, PgpCore/PGP.cs
=> Add optional throwIfEncrypted to Verify methods.

.github/workflows/analyze.yml, .github/workflows/build.yml, PgpCore.Tests/PgpCore.Tests.csproj, PgpCore.Tests/TestFactory.cs, PgpCore.Tests/UnitTests/UnitTestsAsync.cs, PgpCore.Tests/UnitTests/UnitTestsSync.cs, PgpCore/Abstractions/IPGP.InspectAsync.cs, PgpCore/Abstractions/IPGP.InspectSync.cs, PgpCore/Abstractions/IPGP.KeyAsync.cs, PgpCore/Abstractions/IPGP.cs, PgpCore/Models/PGPInspectResult.cs, PgpCore/Models/PgpInspectBaseResult.cs, PgpCore/PGP.EncryptAsync.cs, PgpCore/PGP.EncryptSync.cs, PgpCore/PGP.InspectAsync.cs, PgpCore/PGP.InspectSync.cs, PgpCore/PGP.KeyAsync.cs, PgpCore/PGP.cs, PgpCore/PgpCore.csproj
Adding methods to inspect a PGP message.
#143
=> Add inspect methods

PgpCore.Tests/TestFactory.cs, PgpCore.Tests/UnitTests/UnitTestsAsync.cs, PgpCore/PGP.VerifyAsync.cs, PgpCore/PGP.VerifySync.cs
=> fix stream output

PgpCore/PGP.EncryptAsync.cs, PgpCore/PGP.EncryptSync.cs, PgpCore/PGP.SignAsync.cs, PgpCore/PGP.SignSync.cs, PgpCore/PgpCore.csproj
=> Set fileinfo name when present
