mattosaurus/PgpCore

PgpCore/PgpCore.csproj

Hi, great work! 
What do you think about changing the target framework to .NET Standard 1.3 to improve compatability?
The only dependency BouncyCastle.NetCore targets .NET Standard 1.3.
My use case is Azure Functions which did not work with a .NET Core library but im sure there are others as well. 
I have done some testing with a console app and an Azure Function and everything seems to be working fine.

Change target framework to .NET Standard 1.3?

---

PgpCore/EncryptionKeys.cs
PgpCore/PGP.cs
PgpCore/PgpCore.csproj
PgpCore/Utilities.cs

- changed ReadPublicKey to public, since it my be useful to use it elsewhere. ( I personally need it 👍 )
- moving ReadPublicKey to Utilities reduced redundancy since it was declared multiple times.

Moved ReadPublicKey to Utilities

---

PgpCore.Tests/UnitTests.cs
PgpCore/PGP.cs

Hey, great library btw.
I was trying to use `pgp.DecryptAndVerify()` and was receiving the error `invalid header encountered`. 
I wrote the test to see if it was something I was doing wrong and got the same error.
- Noticed that in other places a decoded stream is passed to ExtractPublicKeyEncryptedData.
- The message is already decrypted in the helper methods.

DecryptAndVerify fixes

---

PgpCore.Tests/PgpCore.Tests.csproj
PgpCore.Tests/UnitTests/UnitTestsAsync.cs
PgpCore.Tests/UnitTests/UnitTestsSync.cs
PgpCore.Tests/xunit.runner.json
PgpCore/PGP.cs
PgpCore/PgpCore.csproj
PgpCore/Utilities.cs

I ran into an issue trying to encrypt a file using a key file that was on a read-only file system. This fixes that issue.

Open keys and input files with read-only access

---

PgpCore/PGP.cs

Also adding helpful exception with message related to input parameter.
Issue: mattosaurus/PgpCore#57

Sanity check for variable before use

---

PgpCore/PgpCore.csproj
PgpCore/Utilities.cs

To allow use of this utility method for public keys not in a file (i.e. from a secrets manager)

Expose ReadPublicKey from stream as public

---

PgpCore/PgpCore.csproj

CSProj files have been updated to enable SourceLink in your nuget
---
*[This pull request was created with an automated workflow]*
I noticed that your repository and Nuget package are important for our .NET community, but you still haven't enabled SourceLink.
**We have to take 2 steps:**
1) Please approve this pull request and make .NET a better place for .NET developers and their debugging.
2) **Then just upload the .snupkg file** to https://www.nuget.org/ (now you can find the snupkg file along with the .nuget file)
You can find more information about SourceLine at the following links  
https://github.com/dotnet/sourcelink
https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx
If you are interesting about this automated workflow …

[PR] The proj files have been updated to enable SourceLink

---

PgpCore/Utilities.cs

When `s.GetHashedSubPackets()` is null the NullPointerException is thrown in line 431

Avoid NullPointerException

---

PgpCore/EncryptionKeys.cs
PgpCore/IEncryptionKeys.cs
PgpCore/PGP.cs

This is the first part, getting the ClearSign, Encrypted, etc. using a new interface.
I toyed with the idea of an abstract class, but my feeling is that there will be another method as part of this next phase for getting the right keys when multiple are supplied, so it felt better as an interface.  This also allows implementors to add in things like storing the keys in a database easier.
The only advantage I could see for an abstract class was the having some private helpers, but that seemed like a stretch.

Refactored to allow Encryption keys to be supplied In-Memory #65

---

PgpCore.Tests/PgpCore.Tests.csproj
PgpCore.Tests/UnitTests/UnitTestsAsync.cs
PgpCore/PgpCore.csproj
README.md

When a library targets .NET Standard, there is no need to multi target netcoreapp versions that implement  the targeted .NET Standard version. This only makes the NuGet package grow in size without any added benefit.
The reason why you would multi-target is to take advantage of APIs in .NET Core that are not available in .NET Standard. This is not the case for this project where all APIs used are compatible with .NET Standard 2.0 (including the Portable.BouncyCastle dependency).
Also, by targeting .NET Standard 2.0, this makes PgpCore compatible with .NET Framework 4.7.2 and 4.8.
The README has also been updated to reflect that change.

Target .NET Standard 2.0 exclusively

---

PgpCore/IPGPEncrypt.cs
PgpCore/IPGPEncryptAsync.cs
PgpCore/IPGPSign.cs
PgpCore/IPGPSignAsync.cs
PgpCore/PGP.cs
PgpCore/PgpCore.csproj

EncryptionKeys property now used to store reference to encryption keys rather than using the paths or streams directly.

Add EncryptionKeys property to PGP

---

PgpCore.Tests/UnitTests/UnitTestsAsync.cs
PgpCore.Tests/UnitTests/UnitTestsSync.cs
PgpCore/PGP.cs

When running DecryptAndVerify on an encrypted file that is also compressed the verification part fails with a PgpException and a message stating 'File was not signed.'
By simply letting the process continue and be picked up by the remainder of the current method the signature can be verified correctly. See the added tests to verify functionality.

Verify signature for compressed files

---

PgpCore/PGP.cs
PgpCore/StreamHelper.cs

Allow the user to pass keys and messages into methods as ASCII armor format, and to get armor format back using simple strings.
This means the user does not have to worry about creating `Stream`s etc. if they just have a key and message in memory to work with.
(also a Visual Studio plugin removed some trailing whitespace apparently too)

Add ASCII armor support

---

PgpCore.Tests/UnitTests/UnitTestsSync.cs
PgpCore/PGP.cs

When provided with an encrypted and compressed file, DecryptAndVerify happily decrypts the file even though its not signed.
Added a failing unit test and updated it to throw a PgpException like its uncompressed counterpart

DecryptAndVerify verify that a signature exist for compressed files

---

PgpCore/PGP.cs

* `inputFileStream` instances are already disposed because they are inside a `using` block.
* `inputStream` should not be disposed because it's the caller responsibility to dispose the input stream.
* `secretOut` and `publicOut` should not be disposed , only the `ArmoredOutputStream` wrapper should be disposed.

Do not dispose streams that should not be disposed

---

PgpCore/Utilities.cs

When I used a key ring containing a masterkey for signing and a subkey for encryption, the library always used the masterkey, even though it did not contain keyflags for encryption.
After some digging, I found this check in the ReadPublicKey method, where only masterkeys are checked. After cloning and removing the masterkey check, the library encrypts with the subkey as expected.

Allow for subkeys to be used for encryption

---

PgpCore/EncryptionKeys.cs
PgpCore/IEncryptionKeys.cs
PgpCore/IPGPEncrypt.cs
PgpCore/PGP.cs
PgpCore/Streams.cs
PgpCore/Utilities.cs

Library will look for appropriate KeyFlags for encryption and signing keys respectively. Some code cleanup.
So @mattosaurus.. about that rewrite 😅
The commit started as simply just getting the library to find and use subkeys in the keyrings appropriately. It grew, however, as I saw some possibilities for refactoring, clarity, and other "small" changes which ended up at ***looks at commit*** ~7 000 additions and deletions..
I tried to leave the Interfaces alone as to avoid breaking changes, but it still remains a large amount of changes. I probably should have divided it up in more "bite-sized" commits, but alas, here we are.
Also, as far as I can see, it does pass the unit tests. 
Hope you will take a look!

Rewrite for subkey support

---

PgpCore.Tests/UnitTests/LegacyUnitTestsAsync.cs
PgpCore.Tests/UnitTests/LegacyUnitTestsSync.cs
PgpCore.Tests/UnitTests/UnitTestsAsync.cs
PgpCore.Tests/UnitTests/UnitTestsSync.cs
PgpCore/PGP.cs
PgpCore/PgpCore.csproj

I've added additional versions of VerifyClearArmoredString+Async to output the content as part of performing verification.
I've also remove an unused variable (outputStream) in the VerifyArmoredString methods (which admittedly could have been a separate commit).
This (at least partially) addresses #77.

Add ability to extract clear-signed content when verifying signature

---

PgpCore/CompositeDisposable.cs
PgpCore/DisposableExtensions.cs
PgpCore/PGP.cs

This resolves the "Cannot Access a closed stream" error during decryption by delaying disposal of all streams returned from `GetDataStream`.
Fixes #140
Adapted from #155

Fix incompatibility w/ Portable.BouncyCastle 1.9.0

---

PgpCore.Tests/UnitTests/UnitTestsSync.cs
PgpCore/EncryptionKeys.cs
PgpCore/IEncryptionKeys.cs
PgpCore/PGP.cs
PgpCore/PgpPublicKeyRingWithPreferredKey.cs
PgpCore/Utilities.cs

#238 (partly)
So, I've changed how public keys are managed in `EncryptionKeys` and how they are used in Encryption and some Verification in `PGP`.
Summary of the main changes in this PR:
- Every public key ring is now stored as a collection of a new wrapper class - `PgpPublicKeyRingWithPreferredKey` (I'm still open for better name suggestions). This class stores the public key ring, the default key (using the already existing algorithm to find the 'best' key) and a preferred key, which can be set by the user using `EncryptionKeys.UseEncryptionKey(_some_keyId_)`
- In the encryption methods, for every known public key ring (a.k.a. recipient), PGP uses the preferred key if it's set, otherwise the default key.
- When verifying encrypted data, it will look for a matching key in any of the …

Rework to support usage of encryption subkeys

---

.github/workflows/analyze.yml
PgpCore/PGP.cs
PgpCore/PgpCore.csproj

Don't dispose compressed ouitput stream

---

PgpCore/Abstractions/IPGP.EncryptAsync.cs
PgpCore/Abstractions/IPGP.EncryptSync.cs
PgpCore/Abstractions/IPGP.SignAsync.cs
PgpCore/Abstractions/IPGP.SignSync.cs
PgpCore/Helpers/Utilities.cs
PgpCore/PGP.EncryptAsync.cs
PgpCore/PGP.EncryptSync.cs
PgpCore/PGP.SignAsync.cs
PgpCore/PGP.SignSync.cs
PgpCore/PGP.cs
PgpCore/PgpCore.csproj

Add old pgp format support

---

PgpCore/PGP.EncryptAsync.cs
PgpCore/PGP.EncryptSync.cs
PgpCore/PGP.InspectAsync.cs
PgpCore/PGP.InspectSync.cs
PgpCore/PGP.RecipientsSync.cs
PgpCore/PGP.SignAsync.cs
PgpCore/PGP.SignSync.cs

Hi,
This pull request includes minor adjustments in C# code related to XML comments. The changes mainly concern minor typos and adding missing comments for parameters.
Thank you in advance  for taking the time to review this pull request. 
Best regards,
Aymeric
-  Correction of minor typos in XML comments.
-  "compatability" -> "compatibility"
-  "arbitary" -> "arbitrary"
-  Added missing <param> tags.

Minor correction of XML comments

---

README.md

The given example for GenerateKey doesn't work if copy-pasted. 
The error:
`Argument 1: cannot convert from 'string' to 'System.IO.FileInfo'	ImportExport.EncryptionHelper`
I've updated the readme to pass a FileInfo object into the call instead of a string

Update readme to fix GenerateKey example command

---

PgpCore.Tests/UnitTests/UnitTestsSync.cs
PgpCore/Models/EncryptionKeys.cs
PgpCore/PGP.EncryptSync.cs
PgpCore/PGP.SignAsync.cs
PgpCore/PGP.SignSync.cs

Hi,
This pull request addresses some minor code adjustments in C# code and XML comments.
Thank you for your attention to these changes.
Best regards,
Aymeric
- Removed unnecessary `armor` parameter from the method documentation.
- Renamed the method `UseEncrytionKey` to `UseEncryptionKey`.

Minor correction of XML comments and method renaming (UseEncrytionKey to UseEncryptionKey)
